var data = {
    "facts": [
        "En 1930, el árbitro John Langenus exigió un seguro de vida y un barco listo en el puerto para escapar si la final terminaba en caos. 🚢🛡️",
        "Héctor Castro fue campeón con Uruguay en 1930 anotando en la final a pesar de que le faltaba el antebrazo derecho por una sierra. 🇺🇾💪",
        "México no jugó de verde en su debut de 1930; usaron uniformes color guinda (rojo oscuro). 🇲🇽👕",
        "El mexicano Manuel Rosas hizo historia al marcar el primer autogol y el primer gol de penal en un Mundial (1930). 🥅📋",
        "Mussolini eligió personalmente a los árbitros de Italia en 1934 para asegurar el triunfo del régimen fascista. 🇮🇹🤨",
        "Giuseppe Meazza anotó el penal que llevó a Italia a la final de 1938 mientras se sostenía los pantalones porque se le cayeron. 🇮🇹🩳",
        "El brasileño Leônidas marcó un gol descalzo en 1938; su bota se rompió en el lodo y el árbitro no lo notó. 🇧🇷👣",
        "Indonesia es el país que menos partidos ha jugado en la historia de los mundiales: solo uno en 1938. 🇮🇩🗺️",
        "Durante la II Guerra Mundial, el trofeo se ocultó en una caja de zapatos bajo la cama de un directivo italiano. 👟🏆",
        "En Brasil 1950, India se retiró porque la FIFA no les permitió jugar descalzos. 🇮🇳👣",
        "El 'Maracanazo' en 1950 causó tal impacto que Brasil cambió su uniforme blanco por el actual amarillo y verde. 🇧🇷🏟️",
        "Uruguay ganó el mundial de 1950 sin haber ganado la final, ya que se definió por un grupo final de todos contra todos. 🇺🇾📊",
        "El partido con más goles fue el Austria 7-5 Suiza en 1954; se jugó a 40 grados centígrados. 🇦🇹🇨🇭",
        "Just Fontaine tiene el récord de más goles en un solo mundial: 13 goles en Suecia 1958. 🇫🇷⚽",
        "Pelé es el campeón más joven de la historia, ganando con solo 17 años y 249 días en 1958. 🇧🇷👑",
        "En 2026, el Estadio Azteca será el primero en la historia en inaugurar tres mundiales (70, 86, 26). 🇲🇽🏟️",
        "El sensor de 500Hz dentro del balón de 2026 enviará datos 500 veces por segundo para detectar fueras de juego. ⚽🤖",
        "El Mundial 2026 será el primero con 48 selecciones, un aumento del 50% respecto a los torneos anteriores. 📈🌎",
        "Philadelphia es sede del Mundial 2026 coincidiendo con los 250 años de la Independencia de EE. UU. 🇺🇸🔔",
        "El Lumen Field de Seattle (sede 2026) es considerado el estadio más ruidoso del mundo por su diseño. 🔊📢",
        "La final del Mundial 2026 será en el MetLife Stadium de Nueva Jersey el 19 de julio de 2026. 🏟️🗓️"
        "En 1930, el árbitro John Langenus exigió un seguro de vida y un barco listo en el puerto para escapar si la final terminaba en caos. 🚢🛡️",
        "Héctor Castro fue campeón con Uruguay en 1930 anotando en la final a pesar de que le faltaba el antebrazo derecho por una sierra. 🇺🇾💪",
        "México no jugó de verde en su debut de 1930; usaron uniformes color guinda (rojo oscuro). 🇲🇽👕",
        "El mexicano Manuel Rosas hizo historia al marcar el primer autogol y el primer gol de penal en un Mundial (1930). 🥅📋",
        "Mussolini eligió personalmente a los árbitros de Italia en 1934 para asegurar el triunfo del régimen fascista. 🇮🇹🤨",
        "Giuseppe Meazza anotó el penal que llevó a Italia a la final de 1938 mientras se sostenía los pantalones porque se le cayeron. 🇮🇹🩳",
        "El brasileño Leônidas marcó un gol descalzo en 1938; su bota se rompió en el lodo y el árbitro no lo notó. 🇧🇷👣",
        "Indonesia es el país que menos partidos ha jugado en la historia de los mundiales: solo uno en 1938. 🇮🇩🗺️",
        "Durante la II Guerra Mundial, el trofeo se ocultó en una caja de zapatos bajo la cama de un directivo italiano. 👟🏆",
        "En Brasil 1950, India se retiró porque la FIFA no les permitió jugar descalzos. 🇮🇳👣",
        "Alcides Ghiggia silenció al Maracaná en 1950; es el autor del gol más famoso de la historia de Uruguay. 🇺🇾🏟️",
        "El partido con más goles fue el Austria 7-5 Suiza en 1954; se jugó a 40 grados centígrados. 🇦🇹🇨🇭",
        "Pelé es el campeón más joven de la historia, ganando con solo 17 años en Suecia 1958. 🇧🇷👑",
        "En 1962, la 'Batalla de Santiago' entre Chile e Italia fue tan violenta que necesitó intervención policial. 🇨🇱🇮🇹",
        "El trofeo Jules Rimet fue robado en 1966 y encontrado por un perro llamado Pickles en un jardín. 🐶🏆",
        "México 1970 fue el primer mundial transmitido a color y el primero en usar tarjetas amarillas y rojas. 📺🟥",
        "El 'Gol del Siglo' de Maradona contra Inglaterra en 1986 recorrió 60 metros y eludió a 6 rivales. 🇦🇷⚽",
        "Roger Milla celebró sus goles en 1990 bailando en el banderín de esquina, convirtiéndose en icono a los 38 años. 🇨🇲🕺",
        "En 1994, el estadounidense Andres Escobar fue asesinado tras anotar un autogol; una tragedia que marcó al fútbol. 🇨🇴💔",
        "Zinedine Zidane cerró su carrera con un cabezazo a Materazzi en la final de 2006, una de las imágenes más famosas. 🇫🇷🇮🇹",
        "En 2026, el Estadio Azteca será el único en el mundo en haber inaugurado tres mundiales distintos. 🇲🇽🏟️",
        "El sensor de 500Hz dentro del balón de 2026 enviará datos 500 veces por segundo para detectar fueras de juego. ⚽🤖",
        "Se jugarán 104 partidos en total en 2026, lo que lo convierte en el mundial más largo de la historia (39 días). 🗓️🏆",
        "FBI y policía mexicana formarán una fuerza de seguridad conjunta para garantizar la paz en 2026. 👮‍♂️🛂",
        "El estadio de Dallas (AT&T Stadium) planea proyectar hologramas gigantes de los jugadores en la cancha. 🏟️🧬",
        "El Lumen Field de Seattle es tan ruidoso que sus gritos han sido registrados por sismógrafos como mini terremotos. 🔊📢",
        "La final de 2026 se jugará en el MetLife Stadium de Nueva Jersey, con capacidad para 82,500 personas. 🗽🏟️",
        "Por primera vez, 48 países participarán en el torneo, un aumento masivo desde los 32 habituales. 🌎📊",
        "El balón oficial de 2026 estará conectado a la red Wi-Fi 7 de los estadios para estadísticas en tiempo real. 🛰️⚽",
        "Se estima que más de 6 millones de fans viajarán entre México, USA y Canadá para el torneo. ✈️🎟️",
        "Canadá albergará por primera vez partidos de un Mundial masculino en Toronto y Vancouver. 🇨🇦⚽",
        "El sorteo oficial de grupos en 2025 usará un software de IA para optimizar los viajes de los equipos. 🤖📋",
        "Philadelphia será sede clave coincidiendo con el 250 aniversario de la Independencia de EE. UU. 🇺🇸🔔",
        "El aire acondicionado del estadio de Houston puede bajar la temperatura 15 grados en solo 10 minutos. ❄️🏟️",
        "El himno oficial de 2026 mezclará ritmos regionales mexicanos, pop estadounidense y folk canadiense. 🎶🌎"
    ]
}